version: "3.5"
services:
  sequencer-feed:
    build:
      context: build
      args:
        UPSTREAM_VERSION: v2.1.3-e815395
    environment:
      FEED_INPUT_URL: "wss://arb1.arbitrum.io/feed"
      FEED_OUTPUT_PORT: "9642"
      EXTRA_OPTS: ""
    image: "sequencer-feed.arbitrum-nitro-relay.public.dappnode.eth:1.0.1"
    restart: unless-stopped
